import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react'
import { API_URL } from '../utils/paths'

const Home: NextPage<IProps> = ({api}) => {
  useEffect(() => {
    fetch(`http://${api}`)
      .then(res => res.json())
      .then(json => console.info(json))
      .catch(err => console.error(err))
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl">
        <h1>
          NextJS
        </h1>
        <p>
          { `${api}` }
        </p>
      </div>
    </div>
  )
}

interface IProps {
  api: string,
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      api: API_URL
    }
  }
}

export default Home
