import type { GetServerSideProps, NextPage } from 'next'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import { API_URL } from '../utils/paths'

interface ITestData {
  id: number,
  name: string,
  account: string,
}

const Home: NextPage<IProps> = ({api}) => {
  const [test, setTest] = useState<ITestData[]>([]);
  const [count, setCount] = useState(1);

  const doQuery = (count: number) => {
    fetch(`http://${api}?count=${count}`)
      .then(res => res.json())
      .then(json => {
        console.info(json);
        setTest(json)
      })
      .catch(err => console.error(err))
  }

  useEffect(() => {
    doQuery(1);
  }, []);

  return (
    <div className="flex flex-col content-center justify-center">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-4xl text-center">
        <h1>
          NextJS - { `${api}` }
        </h1>
        <div>
          <input
            className="bg-slate-700 text-white border-black border-2 rounded-md px-2 w-32"
            type="number"
            value={count}
            onChange={e => setCount(e.currentTarget.valueAsNumber)}
          />
          <button
            className="bg-slate-700 text-white rounded-md hover:bg-slate-800 px-2 py-1 mx-2"
            onClick={() => doQuery(count)}
          >
            Get
          </button>
        </div>
        <div className="flex flex-row flex-wrap mx-3 mt-2">
          {
            test.map(t => (
              <div key={t.id + Math.random()} className="bg-slate-800 text-white p-4 rounded-md mx-4 mt-2">
                <h1>{t.name}</h1>
                <h2>{t.account}</h2>
              </div>
            ))
          }
        </div>
      </div>
    </div>
  )
}

interface IProps {
  api: string,
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  return {
    props: {
      api: API_URL
    }
  }
}

export default Home
